const backendProd = {
  beUrl: 'http://oih.kpn.org:8888/api/v2/',
  apptoken: 'cfe595a88b10a4aa5ef460660f6240bd3a72f89e411d31169579444145119f89',
  sessionUrl: 'user/session',
  system: 'system/user?related=user_to_app_to_role_by_user_id&order=name%20ASC',
  tasks: 'funnel/_table/funnel.tasks',
  remarks: 'funnel/_table/funnel.remarks',
  assumptions: 'funnel/_table/funnel.assumptions',
  checklists: 'funnel/_table/funnel.checklists',
  stageGates: 'funnel/_table/funnel.stagegates',
  votes: 'funnel/_table/funnel.votes',
  passrst:'user/password',
  register:'user/register',
  onboarding: 'funnel/_table/funnel.onboarding',
  defUser: '',
  defPass: '',
};

const backendDev = {
  beUrl: 'http://oih.kpn.org:8888/api/v2/',
  apptoken: 'cfe595a88b10a4aa5ef460660f6240bd3a72f89e411d31169579444145119f89',
  sessionUrl: 'user/session',
  system: 'system/user?related=user_to_app_to_role_by_user_id&order=name%20ASC',
  tasks: 'funnel_dev/_table/funnel.tasks',
  remarks: 'funnel_dev/_table/funnel.remarks',
  assumptions: 'funnel_dev/_table/funnel.assumptions',
  checklists: 'funnel_dev/_table/funnel.checklists',
  stageGates: 'funnel_dev/_table/funnel.stagegates',
  votes: 'funnel_dev/_table/funnel.votes',
  passrst:'user/password',
  register:'user/register',
  onboarding: 'funnel_dev/_table/funnel.onboarding',
  defUser: '',
  defPass: '',
};
const backendAga = {
  beUrl: 'http://oih.kpn.org:8888/api/v2/',
  apptoken: 'cfe595a88b10a4aa5ef460660f6240bd3a72f89e411d31169579444145119f89',
  sessionUrl: 'user/session',
  system: 'system/user?related=user_to_app_to_role_by_user_id&order=name%20ASC',
  tasks: 'funnel_dev/_table/funnel.tasks',
  remarks: 'funnel_dev/_table/funnel.remarks',
  assumptions: 'funnel_dev/_table/funnel.assumptions',
  checklists: 'funnel_dev/_table/funnel.checklists',
  stageGates: 'funnel_dev/_table/funnel.stagegates',
  votes: 'funnel_dev/_table/funnel.votes',
  passrst:'user/password',
  register:'user/register',
  defUser: 'agamemnon.aspirtakis@kpn.com',
  onboarding: 'funnel_dev/_table/funnel.onboarding',
  defPass: 'a224935a',
};
const backendAgaSTG = {
  beUrl: 'http://oih.kpn.org:8888/api/v2/',
  apptoken: 'cfe595a88b10a4aa5ef460660f6240bd3a72f89e411d31169579444145119f89',
  sessionUrl: 'user/session',
  system: 'system/user?related=user_to_app_to_role_by_user_id&order=name%20ASC',
  tasks: 'FunnSTG/_table/funnel.tasks',
  remarks: 'FunnSTG/_table/funnel.remarks',
  assumptions: 'FunnSTG/_table/funnel.assumptions',
  checklists: 'FunnSTG/_table/funnel.checklists',
  stageGates: 'FunnSTG/_table/funnel.stagegates',
  passrst:'user/password',
  onboarding: 'FunnSTG/_table/funnel.onboarding',
  votes: 'FunnSTG/_table/funnel.votes',
  register:'user/register',
  defUser: 'agamemnon.aspirtakis@kpn.com',
  defPass: 'a224935a',
};
const backendSTG = {
  beUrl: 'http://oih.kpn.org:8888/api/v2/',
  apptoken: 'cfe595a88b10a4aa5ef460660f6240bd3a72f89e411d31169579444145119f89',
  sessionUrl: 'user/session',
  system: 'system/user?related=user_to_app_to_role_by_user_id&order=name%20ASC',
  tasks: 'FunnSTG/_table/funnel.tasks',
  remarks: 'FunnSTG/_table/funnel.remarks',
  assumptions: 'FunnSTG/_table/funnel.assumptions',
  checklists: 'FunnSTG/_table/funnel.checklists',
  stageGates: 'FunnSTG/_table/funnel.stagegates',
  onboarding: 'FunnSTG/_table/funnel.onboarding',
  votes: 'FunnSTG/_table/funnel.votes',
  passrst:'user/password',
  register:'user/register',
  defUser: '',
  defPass: '',
};



const backend = backendAgaSTG;
export {backend} ;